version: '3.3'
services:
    db:
        image: postgres:12
        container_name: postgres
        volumes:
            - pgdata:${PGDATA}
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: ${PGDATA}
            PGPORT: ${PGPORT}
        ports:
            - ${PGPORT}:${PGPORT}
    keystone:
        build:
            context: ..
            dockerfile: ./docker/keystone.dev.dockerfile
        command: yarn dev
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
        volumes:
            - ../keystone:/app
volumes:
    pgdata:
